// Code generated by 'yaegi extract github.com/xmapst/go-hotfix'. DO NOT EDIT.

package symbols

import (
	"github.com/xmapst/go-hotfix"
	"reflect"
)

func init() {
	Symbols["github.com/xmapst/go-hotfix/hotfix"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ApplyFunc": reflect.ValueOf(hotfix.ApplyFunc),

		// type definitions
		"FuncPatch": reflect.ValueOf((*hotfix.FuncPatch)(nil)),
	}
}
