// Code generated by 'yaegi extract github.com/xmapst/go-hotfix/example/handler'. DO NOT EDIT.

package symbols

import (
	"github.com/xmapst/go-hotfix/example/handler"
	"reflect"
)

func init() {
	Symbols["github.com/xmapst/go-hotfix/example/handler/handler"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(handler.New),

		// type definitions
		"HttpSvc": reflect.ValueOf((*handler.HttpSvc)(nil)),
	}
}
